[package]
name = "template"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8.0.0"
tracing = { version = "0.1.41", features = ["log"] }
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.19", features = ["registry", "env-filter"] }
